name: CI
on: push
jobs:
  lint:
    run-on: ubuntu-latest
    step:
    -user: action /checkout@v4
    -run: echo "lint step running"
  test:
     run-on: ubuntu-latest
     steps:
       -uses: action/checkout@v4
       -run: echo "test step running"
